### ISSUE TITLE
Is it a good practice to keep GET-ting from server with fixed interval?

### ISSUE THREAD

**Issue by AugustusZ** [AugustusZ/twitter-wall#9]
Afraid not. Two better solutions:

## Dynamic Interval  

If a client polls periodically (as implemented currently), it will be better to do it with dynamic interval. For each incremental update JSON `incrementalUpdate` responded, the client calculates average interval `interval` between the tweets in its `data` field, and does not request for a new `incrementalUpdate` again until such an `interval` long time passes.

Considering these situations: **slumping** vs **bursting**, **unpopular** vs **popular**.

## Server Pushing

Some research is required to know how to do it. Keyword: **real-time**

**Comment by sathyaprasad** [comment]
Check out https://socket.io/
